// Mocks generated by Mockito 5.4.5 from annotations
// in qr_auth_app/test/features/auth/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qr_auth_app/core/pigeon/auth_qr_api.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BiometricApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricApi extends _i1.Mock implements _i2.BiometricApi {
  @override
  _i3.Future<_i2.AuthResult> authenticate(_i2.AuthConfig? arg_config) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [arg_config]),
            returnValue: _i3.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#authenticate, [arg_config]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#authenticate, [arg_config]),
              ),
            ),
          )
          as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
